name: setup

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up the Learning Space
        uses: lpmi-13/learning-space-single-setup@v1.0.0
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        with:
          path: ./.learning/materials.yml
